shotgun/shotgun/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'shotgun.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^shotgun_app/', include('shotgun_app.urls', namespace='shotgun_app')),
    url(r'^admin/', include(admin.site.urls)),
]

shotgun/shotgun_app/urls.py
from django.conf.urls import patterns, url

from shotgun_app import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^create$', views.create, name='create'),
    url(r'^index$', views.create_handler, name='create_handler'),
    url(r'^landing$', views.landing, name='landing'),
    url(r'^chats$', views.chats, name='chats'),
    url(r'^settings$', views.settings, name='settings'),
)

shotgun/shotgun_app/models.py
from django.db import models

class Users(models.Model):
    user_id = models.AutoField(primary_key=True)
    image = models.CharField(max_length=200)
    email = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

class Events(models.Model):
    event_id = models.AutoField(primary_key=True)
    author_id = models.IntegerField()
    event_name = models.CharField(max_length=200)
    event_description = models.CharField(max_length=1000)
    publish_time = models.DateTimeField()
    event_time = models.DateTimeField(null=True, blank=True)
    location = models.CharField(max_length=200,default='')
    privacy = models.CharField(max_length=50)
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.event_name

class Attending(models.Model):
    event_id = models.AutoField(primary_key=True)
    user_id = models.IntegerField()
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.event_id

class Friends(models.Model):
    friendship_id = models.AutoField(primary_key=True)
    user1_id = models.IntegerField()
    user2_id = models.IntegerField()
    conversation = models.CharField(max_length=100000)
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.friendship_id

shotgun/shotgun_app/views.py
from django.shortcuts import render
from django.template import RequestContext, loader
from django.utils import timezone
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from shotgun_app.models import Users,Events,Attending, Friends
import datetime

def index(request):
    latest_event_list = Events.objects.all().order_by('-publish_time')[:15]
    latest_author_list = []
    for event in latest_event_list:
    	latest_author_list.append(Users.objects.get(pk = latest_event_list[0].author_id))
    newsfeed = zip(latest_event_list, latest_author_list)
    user = Users.objects.get(pk=1)
    context = {
    	'latest_event_list': latest_event_list,
    	'user': user,
    	'newsfeed': newsfeed
    }
    return render(request, 'shotgun_app/index.html', context)

def chats(request):
    conversations = Friends.objects.filter(pk=1)
    user = Users.objects.get(pk=1)
    context = {
    	'conversations': conversations,
    	'user': user
    }
    return render(request, 'shotgun_app/chats.html', context)

def create(request):
    return render(request, 'shotgun_app/create.html')

def create_handler(request):
    if 1:
        name = request.POST['ename']
        description = request.POST['edescription']
        location = request.POST['location']
        privacy = request.POST['privacy']
        if request.POST['etime'] and request.POST['edate']:
            time = request.POST['etime'].split(':')
            date = request.POST['edate'].split('-')
            time = [int(x) for x in time]
            date = [int(x) for x in date]
            edatetime = datetime.datetime(year=date[0],month=date[1],day=date[2],hour=time[0],minute=time[1])
        else:
            edatetime = None
        if not location:
            location = ''
        user = Users.objects.get(pk=1)
        e = Events(event_name=name, event_description=description, author_id=user.user_id, publish_time=timezone.now(), location=location,privacy=privacy,event_time=edatetime)
        e.save()
        return index(request)

def landing(request):
    return render(request, 'shotgun_app/landing.html')

def settings(request):
	user = Users.objects.get(pk=1)
	context = {
    	'user': user
    }
	return render(request, 'shotgun_app/settings.html', context)
   

shotgun/shotgun_app/templates/shotgun_app/base.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Shotgun</title>

  <meta name="description" content="Social Matching Site">
  <meta name="author" content="Linda Du and Max Lu">
  <meta name="keywords" content="Meet Up, Social Network, Matching, Hang Out, Bored, Find Friends, Fun, Friends">

  <link rel="stylesheet"  type = "text/css" href="{{ STATIC_URL }}bootstrap/css/bootstrap.css"/>
  <link rel="stylesheet" type = "text/css" href="{{ STATIC_URL }}bootstrap/css/style.css"/>

   <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic" rel="stylesheet" type="text/css">

  <script type="text/javascript" src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}main.js"></script>
  <script type="text/javascript" href="static/bootstrap/js/bootstrap.js"></script>

  <!-- favicon -->
  <link rel="icon" type="image/png" href="/img/favicon.png" />
         
  <!-- jQuery from Google -->
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
  <!-- The main JavaScript/CSS Files -->
  <script src="{{ STATIC_URL }}main.js"></script>   

  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

<body>
	<!-- Facebook Javascript SDK -->
	<script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : 1580647128828605,
          xfbml      : true,
          version    : 'v2.0'
        });
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));

      
    </script>

	<!-- begins navbar -->
	<nav class="navbar navbar-default" role="navigation">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/shotgun_app">Shotgun</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active"><a href="#">Newsfeed</a></li>
	        <li><a href="#">Chats</a></li>
	      </ul>
	      <form class="navbar-form navbar-left" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form>
	      <ul class="nav navbar-nav navbar-right">
	      	<li><a href="settings">Settings</a></li>
	      	<li><input id="Log Out" type="button" value="Log Out" onclick="FB.logout(function(response) {});;" /></li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	{% block content %}
	{% endblock content %}
</body>
<footer>
</footer>
</html>

shotgun/shotgun_app/templates/shotgun_app/chats.html
{% extends "shotgun_app/base.html" %}
{% block content %}
    
<div class="left_bar" id="inbox" align="left"></div>
  {% if conversations %}
    {% for convo in conversations %}
      <div id="box">
        <img src="user.image" width="60"height="60">
        {{convo.conversation}}
      </div>
    {% endfor %}
  {% else %}
    <div id="right_main">
      <p>No messages yet!</p>
    </div>
  {% endif %}
<div class="span9" id="conversation" style="height:80%">

{% endblock content %}

shotgun/shotgun_app/templates/shotgun_app/create.html
{% extends "shotgun_app/base.html" %}
{% block content %}


<h3>Create an Event</h3>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'shotgun_app:create_handler' %}" method="post">
{% csrf_token %}

	<p><input name="ename" type="text" placeholder="Event Name" /></p>

	<p><input name="edescription" type="text" placeholder="Event Description" /></p>

	<p>
	Privacy <br/>
    <input type="radio" name="privacy" id="0" value="friends" />&nbsp;&nbsp;friends<br />
    <input type="radio" name="privacy" id="1" value="friends of friends" />&nbsp;&nbsp;friends of friends<br/>
    <input type="radio" name="privacy" id="2" value="errone" />&nbsp;&nbsp;errone<br/>
</p>
<br/>
    Optional: <br/>
    <p><input name="location" type="text" placeholder="Location" /></p>
    Event date: <input type="date" name="edate"> <input type="time" name="etime"> 
<input type="submit" value="Create" />
</form>

{% endblock content %}

shotgun/shotgun_app/templates/shotgun_app/index.html
{% extends "shotgun_app/base.html" %}
{% block content %}


	<div id="container">
    <div id="content">
      <div id="box">
          <a href="#" class="btn btn-default btn-lg" onclick="loadCreateForm()">create an event</a>
          {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
          <form action="{% url 'shotgun_app:create_handler' %}" method="post">
          {% csrf_token %}
        <div id = "create">
        </div>
      </div>
    <br/>
    </div>
    <div id="profile">
        <div id = "picture">
          <img src="smiley.gif" width="125"height="125">
        </div>
        <div id = "information">
          <h2> {{user.name}} </h2>
          Edit profile
        </div>    
      </div>
	  <div id="content">
	    {% if newsfeed %}
    	  {% for item in newsfeed %}
       	    <div id="box">
       	  	  <img src="smiley.gif" width="60"height="60">
       	  	  {{item.1.name}} -  {{item.0.event_name}}<br>
       	  	  {{item.0.event_description}} <br>
       	  	  {{item.0.event_date}} <br>
       	  	  {{item.0.location}} <br>

       	      <div class="fb-like" data-href= {{item.0.event_name}} data-send="true" data-width="450" data-show-faces="true"></div>
    	    </div>
    	  {% endfor %}
	    {% else %}
        <div id="box">
          <p>No events are available.</p>
        </div>
        {% endif %}
      </div>
      
	</div>
	


{% endblock content %}